services:
  # Your FastAPI Application
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs  # Mount logs directory

  # The Redis Server
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    # Optional: Persist data to your host machine so it survives container restarts
    # volumes:
    #   - redis_data:/data

# Optional: Define a volume for Redis persistence
# volumes:
#   redis_data: