global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: "casa-cuenta-api"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
